{% set version = "0.8.0" %}
{% set build = 0 %}

package:
  name: ifcopenshell
  version: {{ version }}

source:
  - url: https://github.com/IfcOpenShell/IfcOpenShell/archive/refs/tags/ifcopenshell-python-{{ version }}.tar.gz
    sha256: 9666e945be059654ef4f29edb8920364c00a191f3123dc3d48ab89409b9e3582

  - url: https://github.com/IfcOpenShell/files/archive/ed6b97983ff1324a0eaec0fd676ab58051cf3059.tar.gz
    folder: test/input
    sha256: 2bf8cabd6364fbb09b4e7351397beb631d47d9574ee89c98510066acec3a58ac

  - url: https://github.com/opensourceBIM/python-mvdxml/archive/83c12fa494b9d6a5a370d8525dc1f76aa5c89d8d.tar.gz
    folder: src/ifcopenshell-python/ifcopenshell/mvd
    sha256: 3a332aae707967e609dcab44a118a88ec270c551e7222eb53fc8ba809e9e7a0d

  - url: https://github.com/IfcOpenShell/svgfill/archive/f9102b1e9f58e2c3bf9923c1eafa0373eeb872f5.tar.gz
    folder: src/svgfill
    sha256: b0b3f3b98a204a7315ec7cca24278600d192bdb7ae8462e10eca0cd0aeaf52d8

  - url: https://github.com/IfcOpenShell/ids-test-files/archive/adadc7740b7337f4cb0935ec8e84ba30ed4ca10d.tar.gz
    folder: src/ifcopenshell-python/test/Sample-BIM-Files
    sha256: d0b86d456a8575d6b72186a01f2fb2ba93b86058ce6b178045a6d11e3468e3f6

  - url: https://github.com/svgpp/svgpp/archive/15da1891e576e8ef66dbe90e8e1a776dccea889d.tar.gz
    folder: src/svgfill/3rdparty/svgpp
    sha256: 5364b6a2d49c37fe3d0669366ec07348378868d1f0d94674cd1af97229adc558


build:
  number: {{ build }}
  skip: true  # [py<39]
  binary_relocation: false  # [osx]
  run_exports:
    - {{ pin_subpackage('ifcopenshell', max_pin='x.x.x') }}


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - ninja
    - swig >=4.1.1
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - libboost-devel
    - occt
    - libxml2
    - cgal-cpp
    - hdf5
    - eigen
    - mpfr
    - nlohmann_json
    - gmp  # [unix]
    - mpir  # [win]
    - zlib
  run:
    - python
    - numpy
    - {{ pin_compatible('occt', max_pin='x.x.x') }}
    - {{ pin_compatible('cgal-cpp', max_pin='x.x') }}


test:
  files:
    - pytest.ini
  source_files:
    - src/ifcopenshell-python/test/Sample-BIM-Files
    - src/ifcopenshell-python/test
  imports:
    - ifcopenshell
  requires:
    - occt * *novtk*  # Ensure that even though compiled against OCCT with VTK, it can still run with OCCT without VTK
    - pytest
    - python-dateutil
    - xmlschema
    - xsdata
    - lxml
    - isodate
    - lark
    - networkx
    - tabulate
    - shapely
  commands:
    - pytest src/ifcopenshell-python/test

about:
  home: https://ifcopenshell.org
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: 'IfcOpenShell is a library to support the IFC file format'
  description: |
    IfcOpenShell
    ============
    
    <p align="center">
    <img src="https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/34901387-e2dd-4a0c-8e38-9ffc32a66cde">
    </p>

    IfcOpenShell is an open source ([LGPL]) software library for working with Industry Foundation Classes ([IFC]). Complete
    parsing support is provided for [IFC2x3 TC1], [IFC4 Add2 TC1], IFC4x1, IFC4x2, and [IFC4x3 Add2]. Extensive geometric support
    is implemented for the IFC releases [IFC2x3 TC1] and [IFC4 Add2 TC1]. Extending with support for arbitrary IFC schemas
    is possible at compile-time when using C++ and at run-time when using Python.
    
    In addition to a C++ and Python API, IfcOpenShell comes with an ecosystem of tools, notably including IfcConvert (an application
    to convert IFC models to other formats), Bonsai (an add-on to Blender providing a graphical IFC authoring platform),
    and many other libraries, CLI apps, and more. Support is also provided for auxiliary standards such as BCF and IDS.
    
    For more information, see:
    
    * [IfcOpenShell Website](http://ifcopenshell.org)
    * [IfcOpenShell Documentation](https://docs.ifcopenshell.org)
      * [IfcOpenShell C++ Installation](https://docs.ifcopenshell.org/ifcopenshell/installation.html)
      * [IfcOpenShell Python Installation](https://docs.ifcopenshell.org/ifcopenshell-python/installation.html)
      * [IfcOpenShell Python Hello World Tutorial](https://docs.ifcopenshell.org/ifcopenshell-python/hello_world.html)
    * [Bonsai Website](https://bonsaibim.org)
    * [Bonsai Documentation](https://docs.bonsaibim.org/index.html)
      * [Add-on Installation](https://docs.bonsaibim.org/quickstart/installation.html)
      * [Exploring an IFC model](https://docs.bonsaibim.org/quickstart/explore_model.html)
    
    Development is sponsored through your generous donations!

    [![Open Collective Contributors](https://img.shields.io/opencollective/all/opensourcebim?label=Sponsors&color=22ce5f)](https://opencollective.com/opensourcebim/)

    Contents
    --------

    <table>
      <tr>
          <td>Name</td>
          <td>Description</td>
          <td>License</td>
          <td>Service</td>
      </tr>
      <tr>
          <td>bcf</td>
          <td>Library to read and write BCF-XML and query OpenCDE BCF-API modules</td>
          <td>LGPL-3.0-or-later</td>
          <td>[![PyPI](https://img.shields.io/pypi/v/bcf-client?label=PyPI&amp;color=006dad)](https://pypi.org/project/bcf-client/)</td>
      </tr>
      <tr>
          <td>bonsai</td>
          <td>Add-on to Blender providing a graphical native IFC authoring platform</td>
          <td>GPL-3.0-or-later</td>
          <td>[![Official](https://img.shields.io/badge/BonsaiBIM.org-Download-70ba35)](https://bonsaibim.org/download.html) [![GitHub Unstable](https://img.shields.io/github/v/release/ifcopenshell/ifcopenshell?filter=bonsai-*&amp;label=GitHub-Unstable&amp;color=f6f8fa)](https://github.com/IfcOpenShell/IfcOpenShell/releases?q=bonsai&amp;expanded=true) [![Chocolatey](https://img.shields.io/chocolatey/v/blenderbim-nightly?label=Chocolatey&amp;color=5c9fd8)](https://community.chocolatey.org/packages/blenderbim-nightly/)</td>
      </tr>
      <tr>
          <td>bsdd</td>
          <td>Library to query the bSDD API</td>
          <td>LGPL-3.0-or-later</td>
          <td>[![PyPI](https://img.shields.io/pypi/v/bsdd?label=PyPI&amp;color=006dad)](https://pypi.org/project/bsdd/)</td>
      </tr>
      <tr>
          <td>ifc2ca</td>
          <td>Utility to convert IFC structural analysis models to Code_Aster</td>
          <td>LGPL-3.0-or-later</td>
          <td></td>
      </tr>
      <tr>
          <td>ifc4d</td>
          <td>Convert to and from IFC and project management software</td>
          <td>LGPL-3.0-or-later</td>
          <td>[![PyPI](https://img.shields.io/pypi/v/ifc4d?label=PyPI&amp;color=006dad)](https://pypi.org/project/ifc4d/)</td>
      </tr>
      <tr>
          <td>ifc5d</td>
          <td>Report and optimise cost information from IFC</td>
          <td>LGPL-3.0-or-later</td>
          <td>[![PyPI](https://img.shields.io/pypi/v/ifc5d?label=PyPI&amp;color=006dad)](https://pypi.org/project/ifc5d/)</td>
      </tr>
      <tr>
          <td>ifcbimtester</td>
          <td>Wrapper for Gherkin based unit testing for IFC models</td>
          <td>LGPL-3.0-or-later</td>
          <td></td>
      </tr>
      <tr>
          <td>ifcblender</td>
          <td>Historic Blender IFC import add-on</td>
          <td>LGPL-3.0-or-later\*</td>
          <td></td>
      </tr>
      <tr>
          <td>ifccityjson</td>
          <td>Convert CityJSON to IFC</td>
          <td>LGPL-3.0-or-later</td>
          <td>[![PyPI](https://img.shields.io/pypi/v/ifccityjson?label=PyPI&amp;color=006dad)](https://pypi.org/project/ifccityjson/)</td>
      </tr>
      <tr>
          <td>ifcclash</td>
          <td>Clash detection library and CLI app</td>
          <td>LGPL-3.0-or-later</td>
          <td>[![PyPI](https://img.shields.io/pypi/v/ifcclash?label=PyPI&amp;color=006dad)](https://pypi.org/project/ifcclash/)</td>
      </tr>
      <tr>
          <td>ifcconvert</td>
          <td>CLI app to convert IFC to many other formats</td>
          <td>LGPL-3.0-or-later\*</td>
          <td>[![Official](https://img.shields.io/badge/IfcOpenShell.org-Download-70ba35)](https://docs.ifcopenshell.org/ifcconvert/installation.html) [![GitHub](https://img.shields.io/github/v/release/ifcopenshell/ifcopenshell?filter=ifcconvert-*&amp;label=GitHub&amp;color=f6f8fa)](https://github.com/IfcOpenShell/IfcOpenShell/releases?q=ifcconvert&amp;expanded=true)</td>
      </tr>
      <tr>
          <td>ifccsv</td>
          <td>Library and CLI app to export and import schedules from IFC</td>
          <td>LGPL-3.0-or-later</td>
          <td>[![PyPI](https://img.shields.io/pypi/v/ifccsv?label=PyPI&amp;color=006dad)](https://pypi.org/project/ifccsv/)</td>
      </tr>
      <tr>
          <td>ifcdiff</td>
          <td>Compare changes between IFC models</td>
          <td>LGPL-3.0-or-later</td>
          <td>[![PyPI](https://img.shields.io/pypi/v/ifcdiff?label=PyPI&amp;color=006dad)](https://pypi.org/project/ifcdiff/)</td>
      </tr>
      <tr>
          <td>ifcfm</td>
          <td>Extract IFC data for FM handover requirements</td>
          <td>LGPL-3.0-or-later</td>
          <td>[![PyPI](https://img.shields.io/pypi/v/ifcfm?label=PyPI&amp;color=006dad)](https://pypi.org/project/ifcfm/)</td>
      </tr>
      <tr>
          <td>ifcmax</td>
          <td>Historic extension for IFC support in 3DS Max</td>
          <td>LGPL-3.0-or-later\*</td>
          <td>[![Official](https://img.shields.io/badge/IfcOpenShell.org-Download-70ba35)](https://docs.ifcopenshell.org/ifcmax.html)</td>
      </tr>
      <tr>
          <td>ifcopenshell-python</td>
          <td>Python library for IFC manipulation</td>
          <td>LGPL-3.0-or-later\*</td>
          <td>[![Official](https://img.shields.io/badge/IfcOpenShell.org-Download-70ba35)](https://docs.ifcopenshell.org/ifcopenshell-python/installation.html) [![GitHub](https://img.shields.io/github/v/release/ifcopenshell/ifcopenshell?filter=ifcopenshell-python-*&amp;label=GitHub&amp;color=f6f8fa)](https://github.com/IfcOpenShell/IfcOpenShell/releases?q=ifcopenshell-python&amp;expanded=true) [![PyPI](https://img.shields.io/pypi/v/ifcopenshell?label=PyPI&amp;color=006dad)](https://pypi.org/project/ifcopenshell/) [![Anaconda](https://img.shields.io/conda/vn/conda-forge/ifcopenshell?label=Anaconda&amp;color=43b02a)](https://anaconda.org/conda-forge/ifcopenshell) [![Anaconda](https://img.shields.io/conda/vn/ifcopenshell/ifcopenshell?label=Anaconda-Unstable&amp;color=43b02a)](https://anaconda.org/ifcopenshell/ifcopenshell) [![Docker](https://img.shields.io/docker/pulls/aecgeeks/ifcopenshell?label=Docker&amp;color=1D63ED)](https://hub.docker.com/r/aecgeeks/ifcopenshell) [![AUR](https://img.shields.io/aur/version/ifcopenshell?label=AUR&amp;color=1793d1)](https://aur.archlinux.org/packages/ifcopenshell) [![AUR Unstable](https://img.shields.io/aur/version/ifcopenshell-git?label=AUR-Unstable&amp;color=1793d1)](https://aur.archlinux.org/packages/ifcopenshell-git)</td>
      </tr>
      <tr>
          <td>ifcpatch</td>
          <td>Utility to run pre-packaged scripts to manipulate IFCs</td>
          <td>LGPL-3.0-or-later</td>
          <td>[![PyPI](https://img.shields.io/pypi/v/ifcpatch?label=PyPI&amp;color=006dad)](https://pypi.org/project/ifcpatch/)</td>
      </tr>
      <tr>
          <td>ifcsverchok</td>
          <td>Blender Add-on for visual node programming with IFC</td>
          <td>GPL-3.0-or-later</td>
          <td>[![GitHub Unstable](https://img.shields.io/github/v/release/ifcopenshell/ifcopenshell?filter=ifcsverchok-*.*.*.*&amp;label=GitHub-Unstable&amp;color=f6f8fa)](https://github.com/IfcOpenShell/IfcOpenShell/releases?q=ifcsverchok&amp;expanded=true)</td>
      </tr>
      <tr>
          <td>ifctester</td>
          <td>Library, CLI and webapp for IDS model auditing</td>
          <td>LGPL-3.0-or-later</td>
          <td>[![PyPI](https://img.shields.io/pypi/v/ifctester?label=PyPI&amp;color=006dad)](https://pypi.org/project/ifctester/)</td>
      </tr>
    </table>
    
    Contents
    --------

    The IfcOpenShell C++ codebase is split into multiple interal libraries:
    
    <table>
      <tr>
          <td>Name</td>
          <td>Description</td>
          <td>License</td>
      </tr>
      <tr>
          <td>ifcgeom</td>
          <td>Internal library for IfcOpenShell</td>
          <td>LGPL-3.0-or-later\*</td>
      </tr>
      <tr>
          <td>ifcgeom\_schema\_agnostic</td>
          <td>Internal library for IfcOpenShell</td>
          <td>LGPL-3.0-or-later\*</td>
      </tr>
      <tr>
          <td>ifcgeomserver</td>
          <td>Internal library for IfcOpenShell</td>
          <td>LGPL-3.0-or-later\*</td>
      </tr>
      <tr>
          <td>ifcjni</td>
          <td>Internal library for IfcOpenShell</td>
          <td>LGPL-3.0-or-later\*</td>
      </tr>
      <tr>
          <td>ifcparse</td>
          <td>Internal library for IfcOpenShell</td>
          <td>LGPL-3.0-or-later\*</td>
      </tr>
      <tr>
          <td>ifcwrap</td>
          <td>Internal library for IfcOpenShell</td>
          <td>LGPL-3.0-or-later\*</td>
      </tr>
      <tr>
          <td>qtviewer</td>
          <td>Internal library for IfcOpenShell</td>
          <td>LGPL-3.0-or-later\*</td>
      </tr>
      <tr>
          <td>serializers</td>
          <td>Internal library for IfcOpenShell</td>
          <td>LGPL-3.0-or-later\*</td>
      </tr>
    </table>

    [LGPL]: https://github.com/IfcOpenShell/IfcOpenShell/tree/master/COPYING.LESSER "LGPL-3.0-or-later"
    [IFC]: https://technical.buildingsmart.org/standards/ifc/ "IFC"
    [IFC2x3 TC1]: https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ "IFC2x3 TC1"
    [IFC4 Add2 TC1]: https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/ "IFC4 Add2 TC1"
    [Visual Studio]: https://www.visualstudio.com/ "Visual Studio"
    [Visual C++ Build Tools]: http://landinghub.visualstudio.com/visual-cpp-build-tools "Visual C++ Build Tools"
    [MSYS2]: https://msys2.github.io/ "MSYS2"
    [win/readme.md]: https://github.com/IfcOpenShell/IfcOpenShell/tree/master/win/readme.md "win/readme.md"
    [nix/build-all.py]: https://github.com/IfcOpenShell/IfcOpenShell/tree/master/nix/build-all.py "nix/build-all.py"
  doc_url: https://ifcopenshell.org/
  dev_url: https://github.com/IfcOpenShell/IfcOpenShell

extra:
  recipe-maintainers:
    - adrianinsaval
    - looooo
    - Krande
