travis:
  secure:
    BINSTAR_TOKEN: nNDAqH1TXyZB1M7SRVY4xkLkdOrKCD6BEumdz6FIWd6tQ4B/afYUoqoeT4kj4AC0dl2OLxgpm6orzp7W78jXQqEdqRkLqnxyftJimYR4Ha0aqOOXZSy2Yd7KrJX8Fp/R8juehsoU8xcHco9Ye1sPHRzfY/5c1UFJOxcAsUkcowVkdf+ADahT0VtI7/BBIWxkfGGfPRjW0+EVGNTj1a3WxhcpYt1N4LBXXDNMPiKVfMAZLNB/m+qoO4hvICGsk9adxvMeK30bWnsW04caGzin2sKjnSliNsulShHrc2Sj3QRPaUDTUI7bJd/hY2CSdFaXSetdCoAdXQeAtDJTokRfwOcR5ePpakEOjllXsEzV19hSeztgd2HsFVcm5XvEB7damZCWjYO28iXwEzEP9kzBAnkJWBT40+yqMQ3AMjX7ZCVhaGIU2uMDuJPAQhbOgqz9VpvV/d9xbXzFpRU17Ca0HUponAWSXCqa9cD5FTjHubGxggxTR6jrVNPdte7I6lpamzKHQF4bxQ+lfYDvdetnuDy6lnVti966ldFsLTYlXt1+SyJ79dUIhbpDcI4S5eY5Rq+I9HqFGx83Uyg75j5YAuq6T8z0697GDSgJbsJCediPYdV2Z8SmTuEa2EwUAyogVOxdD9Ad2OPMwRugRibzzxOx2OOIblqvCFKx6obRwqo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
